name: KANN
channels:
  - plotly
  - defaults
dependencies:
  - pip=20.0.2
  - future=0.18.3
  - h5py=2.10.0
  - imageio=2.15.0
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - markdown=3.3.7
  - numpy=1.19.5
  - pandas=0.25.3
  - plotly=5.14.1
  - protobuf=3.19.6
  - python=3.6
  - pyyaml=6.0
  - scikit-image=0.17.2
  - scikit-learn=0.24.2
  - scipy=1.5.4
  - tensorboard=1.12.2
  - tensorflow=1.12.0
  - pip:
      - matplotlib==3.3.4
      - seaborn==0.11.2
